name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on
  GOLANGCI_LINT_VERSION: 1.27.0

jobs:

  test:
    strategy:
      matrix:
        go-versions: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - uses: actions/cache@v1
      id: bin
      with:
        path: ~/bin/
        key: golangi-lint-${{ env.GOLANGCI_LINT_VERSION }}
    - name: Install golangci-lint
      if: steps.bin.outputs.cache-hit != 'true'
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/bin/ v${GOLANGCI_LINT_VERSION}
